### PR TITLE
ServerUrl config option

### PR DESCRIPTION
**Pull request by mnasyrov**
Added `serverUrl` config option - an optional URL to an external API server. Useful in case of mobile hybrid apps or when different API and web servers are used.

Added basic EditorConfig settings for js files.

### CODE REVIEW

**Comment by micky2be** [comment]
Could you also update the README file.
Then I'll be able to merge. Like what you did here.

**Comment by mnasyrov** [comment]
Updated 'Configuration' section of README.md.
Also updated a description of the option, is it clear enough?

**Comment by micky2be** [comment]
Thanks, will prepare a release shortly

**Comment by micky2be** [comment]
Sorry for the delay. Part of the release 0.5.0

**Pull request merged**
