### PR TITLE
Added initial step

### PR DESCRIPTION
**Pull request by peteruithoven**
I was confused how to initially check whether the user as logged in. In the end refreshing the session seems like the easiest way to do this. 
This way I'm sure the session is valid and fresh. 
Seems like a good addition to your example.

### CODE REVIEW

**Comment by micky2be** [comment]
That's what `checkExpired` should be used for.
It will trigger a `'login'` event if the user session is still active.

**Comment by peteruithoven** [comment]
But how do you get feedback on that you couldn't login? 

Doing that step manually gave me that feedback. I'm also using Redux and this enabled me to automatically set a `isPending` flag. 
I also didn't understand yet that the token gets refreshed automatically with each call.

**Comment by micky2be** [comment]
On setup of Superlogin there shouldn't be any user interaction yet. So IMO you are suppose to show the non-login state of your app until you get a `login` event.
Adding a call of `superlogin.refresh` after setup is really custom to your liking, this is why I cannot accept your PR.

It's not about if you could or couldn't login but more that you are not logged in.
But I just made a modification to`validateSession` (called by the checkExpired option) that will trigger a `logout` event if the user was not logged in automatically, you could use that event if it helps.

**Comment by peteruithoven** [comment]
> On setup of Superlogin there shouldn't be any user interaction yet. So IMO you are suppose to show the non-login state of your app until you get a login event.

Ah alright, as someone who didn't add logins to front ends before I was having a hard time figuring those strategies out. But when the user starts at a page that requires being logged in, this would mean 2 redirects? First to a login page and then back to that original page. 

That would help in some cases, thanks.

**Comment by micky2be** [comment]
If you work on a SPA this should be pretty trivial. Start with a pending or logout status, if `login` trigger, grab the user data from wherever your system is and display it on screen.

If a user try to access a page that needs to be logged in you can use `authenticated` or `validateSession`.
The latter will check locally and remotely if the session is active.
If the user is logged in, grab the data and show the content. If not, go to login page.

**Comment by peteruithoven** [comment]
Good point. 
But when there isn't a session yet, `checkExpired` simply returns and `validateSession` rejects the promise which is then ignored. Meaning you also need to check authenticated(). I think?
I guess my point is that I could check authenticated(), invent a Pending state, listen to login or logout events or I could simply use a Promise, which is how the rest of the client works. 
I understand that simply using refresh might not be the best solution, but maybe we could create a Promise returning function that does checks authenticated, checkExpored and validateSession?

I do totally understand why you don't want it to be a part of the getting started example. I'm just trying to improve your docs, trying to prevent others struggling with the things I was struggling with.

**Comment by micky2be** [comment]
I'm not sure what you are trying to do, it sounds your trying to do too much for what you need.

`checkExpired` is calling `validateSession` (but then ignored since you are still not logged in anyway).
`validateSession` is calling `authenticated`which check is there is an active session. 
- If there is none, it will reject.
- If there is one, it will check if the session is still active on the server side, and logout and reject if it is not.

Personally all I need is to listen on `login` and `logout` event, configure superlogin, and then call `validateSession` on some specific command of my app to make sure we are still connected,

**Comment by peteruithoven** [comment]
But the validateSession reject is ignored: https://github.com/micky2be/superlogin-client/blob/master/src/index.js#L64-L66
Which means one can't simply wait for the login or logout event?

**Comment by micky2be** [comment]
As I tried to explained, when you configure superlogin. If not authenticated, you are supposed to be on logged out state.
So you'll still get the `login` event if the session is active.

**Comment by micky2be** [comment]
If you really need it, I can trigger a `logout` event on `validateSession` if the authenticated return `false`.

What kind of framework are you using for your app? Angular, React, Vue, something custom?

**Comment by peteruithoven** [comment]
[Redux](http://redux.js.org/) with [React](https://facebook.github.io/react/). And [React Router](https://github.com/rackt/react-router) with [redux-auth-wrapper](https://www.npmjs.com/package/).

> As I tried to explained, when you configure superlogin. If not authenticated, you are supposed to be on logged out state.
> So you'll still get the login event if the session is active.

I understand, but as I said then I also need to check `authenticated()`, not a big problem, but requires more code. It's also an extra step the library user has to learn. The `refresh()`, with it's promise now handles all of this for me, I can call it explicitly (if I do this through Redux it can be a clear Action, which I can easily log like other actions), it has the pending state, when it rejects I send my user to the logout page and when it resolves I can show the app. 

> If you really need it, I can trigger a logout event on validateSession if the authenticated return false.

I'm not sure "logout" is really appropriate, so I do understand that you don't want to emit that when the user never had a session to begin with. 

>  you are supposed to be on logged out state.

Maybe it would be interesting to add this state to the superlogin client? Maybe with a general state changed event. It could start in an `authenticating` state, when there is no session it goes to the `logged-out` state, when there is a session and it's not expired and valid it goes to the `logged-in` state.

**Comment by micky2be** [comment]
You should call `validateSession`, not `refresh`. 
`refresh` will, like its name suggest, refresh your token, postpone the expiration date. For that it will update your couchDb data every time you call it. This sounds a bit overkill for what you need.

I too use Redux, React and React-Rooter. I'm using `validateSession` since it's a promise and trigger `login` and `logout` when needed, and it should be enough for your need as well.

You can use `checkExpired` to trigger the first `login` event on page load and get the session data. So your users are automatically logged in.

**Pull request closed without merging**
