### PR TITLE
Clarification proposal for token refresh

### PR DESCRIPTION
**Pull request by peteruithoven**
See: #8

### CODE REVIEW

**Comment by micky2be** [comment]
Well if you want to clarify the sentence there is more to it then.
It's about an http request made by `superlogin` or by the http api available by `getHttp`.

IMO it's good enough the way it is for a feature list, or you will need to describe all of it:

It will call refresh based on the `refreshThreshold`.
`refreshThreshold` is set to 0.5 by default. Meaning at 50% of the time to leave of the token.
If the token expires after 24 hours, it will call refresh when there is 12 hours or less left. And then give you a new expiration date set to 24 hours in the future.

For that to happen there is a hook on http request that will trigger the refresh when necessary.
You can use the `http` module from superlogin using `getHttp` to make sure your own command will trigger the refresh.
You can also call `validateSession` whenever you like if necessary (e.g: onFocus of the tab or window).

Or of course call refresh yourself when ever you fill it's mandatory for your app.

Alternatively you could even force a refresh on the backend side, when needed. There is also an API for that in there.

There are a lot different possibilities, especially if you add the backend part, it all depends of your needs. But I feel a bit overkill to list them all in the Readme.

**Comment by peteruithoven** [comment]
Good point. But the current docs are basically an api reference. It would be great if it would contain some information on one could do session management. I could make a suggestion based on the information you shared above?

**Comment by micky2be** [comment]
I believe what I described is already in the doc

**Comment by peteruithoven** [comment]
Alright nvm

**Pull request closed without merging**
